#!/usr/bin/perl
#
# write_yaml - Write YAML file; we cannot get ExtUtils::MakeMaker
#              to do this, as we don't use the "dist" target to
#              build the tarball but out own mechanim to deal
#              with the Morgan Stanley source environment.
#
# $Id: write_yaml,v 145.3 2007/11/15 13:02:55 biersma Exp $
#

use strict;
use Getopt::Long;

our %args;
GetOptions(\%args, qw(release=s)) || die "Invalid argument";

open (META, '>', 'meta.yaml') ||
  die "Cannot create output file: $!";
print META <<_END_META_;
meta-spec:
  version: 1.2
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
name:		DB2-Admin
abstract:	Interface to DB2 Administrative API (non-SQL functions)
author:		Hildo Biersma <Hildo.Biersma\@MorganStanley.com>
version:	$args{release}
version_from:	lib/DB2/Admin.pm
installdirs:	site
build_requires:
    Params::Validate:	0.87
configure_requires:
    Params::Validate:	0.87
requires:
    Params::Validate:	0.87
recommends:
    Test::Simple:	0.62
license:	LGPL
distribution_type:	module
generated_by:	$0
_END_META_
;
close(META);

exit(0);
